### ISSUE TITLE
0bcbd51ee6c134bd9871451e973b28ceff17fb05 cannot be found llvm-hs repo

### ISSUE THREAD

**Issue by seanesss** [xldenis/ill#1] opened 2018-03-27 12:10 UTC
Hi Xavier,

Your project looks really interesting and I was hoping to build it locally. But when I tried a `stack build` I got 

```
Cloning 0bcbd51ee6c134bd9871451e973b28ceff17fb05 from https://github.com/xldenis/llvm-hs.git
Cloning into '/Users/sseefried/all-code/2016/scratch/ill/.stack-work/downloaded/cLTbhEDj4oqp'...
remote: Counting objects: 7092, done.
remote: Total 7092 (delta 0), reused 0 (delta 0), pack-reused 7092
Receiving objects: 100% (7092/7092), 1.42 MiB | 85.00 KiB/s, done.
Resolving deltas: 100% (4506/4506), done.
Checking connectivity... done.
Please ensure that commit 0bcbd51ee6c134bd9871451e973b28ceff17fb05 exists within https://github.com/xldenis/llvm-hs.git
```

I had a look and it doesn't seem this commit does exist in that repo.

**Comment by xldenis** [comment] 2018-04-02 12:27
Hey! Thanks for checking the project out! That’s very frustrating. Let me attempt to debug this without my laptop :)

**Comment by xldenis** [comment] 2018-04-02 12:37
@sseefried so I believe the problem is that somehow the commit got rebased?? It should work if you change the stack.yaml sha to `c2acbf8c5a75fc7cdb810aea1ad118742ca7999c`.

**Comment by xldenis** [comment] 2018-05-22 15:20
I'm going to close this issue unless you have any more details to bring up :). Thanks for reporting it though

**Closed as completed** 2018-05-30 12:01 UTC
